export default {
  MOVIES_FETCH_STATUSES: 'MOVIES_FETCH_STATUSES',
  MOVIES_SET_DATA: 'MOVIES_SET_DATA',
  SET_MOVIE: 'SET_MOVIE',
  MOVIES_SET_TOTAL: 'MOVIES_SET_TOTAL',
  MOVIES_SET_LOADING: 'MOVIES_SET_LOADING',
  MOVIES_ERROR: 'MOVIES_ERROR',
  MOVIES_FETCH_DATA: 'MOVIES_FETCH_DATA',
  MOVIES_SAGA_ONSEARCH_ACTION: 'MOVIES_SAGA_ONSEARCH_ACTION',
  FETCH_MOVIE_DETAIL: 'FETCH_MOVIE_DETAIL',
  SET_SIMILAR_MOVIE: 'SET_SIMILAR_MOVIE',
};
