export default {
  POSTS_FETCH_STATUSES: 'POSTS_FETCH_STATUSES',
  POSTS_SET_DATA: 'POSTS_SET_DATA',
  POSTS_SET_TOTAL: 'POSTS_SET_TOTAL',
  POSTS_ERROR: 'POSTS_ERROR',
  POSTS_FETCH_DATA: 'POSTS_FETCH_DATA',
  POSTS_SAGA_ONSEARCH_ACTION: 'POSTS_SAGA_ONSEARCH_ACTION'
};
