export default {
  POSTS_FETCH_STATUSES: 'POSTS_FETCH_STATUSES',
  POSTS_SET_DATA: 'POSTS_SET_DATA',
  POSTS_SET_POST: 'POSTS_SET_POST',
  POSTS_SET_POST_COMMENTS: 'POSTS_SET_POST_COMMENTS',
  POSTS_SET_TOTAL: 'POSTS_SET_TOTAL',
  POSTS_SET_LOADING: 'PPOSTS_SET_LOADING',
  POSTS_ERROR: 'POSTS_ERROR',
  POSTS_FETCH_DATA: 'POSTS_FETCH_DATA',
  POSTS_SAGA_ONSEARCH_ACTION: 'POSTS_SAGA_ONSEARCH_ACTION',
  POSTS_FETCH_POST: 'POSTS_FETCH_POST',
};
