export default {
  STREAMS_FETCH_STATUSES: 'STREAMS_FETCH_STATUSES',
  STREAMS_SET_DATA: 'STREAMS_SET_DATA',
  SET_MOVIE: 'SET_MOVIE',
  STREAMS_SET_TOTAL: 'STREAMS_SET_TOTAL',
  STREAMS_SET_LOADING: 'STREAMS_SET_LOADING',
  STREAMS_ERROR: 'STREAMS_ERROR',
  STREAMS_FETCH_DATA: 'STREAMS_FETCH_DATA',
  STREAMS_SAGA_ONSEARCH_ACTION: 'STREAMS_SAGA_ONSEARCH_ACTION',
  FETCH_MOVIE_DETAIL: 'FETCH_MOVIE_DETAIL',
  SET_SIMILAR_MOVIE: 'SET_SIMILAR_MOVIE',
};
